<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRsAGIR6\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRsAGIR6/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerRsAGIR6.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerRsAGIR6\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerRsAGIR6\appAppKernelProdContainer([
    'container.build_hash' => 'RsAGIR6',
    'container.build_id' => '6fcc958a',
    'container.build_time' => 1696553118,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRsAGIR6');
