<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYg0s4AD\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYg0s4AD/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerYg0s4AD.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerYg0s4AD\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerYg0s4AD\appAppKernelProdContainer([
    'container.build_hash' => 'Yg0s4AD',
    'container.build_id' => '7d7fe644',
    'container.build_time' => 1696553213,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYg0s4AD');
